---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.8.12
  multiple_converge: 2
  enforce_idempotency: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[maven-test::default]
